djangoBlog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""djangoBlog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from __future__ import unicode_literals
from django.conf.urls import url,include
from django.shortcuts import render,HttpResponse,redirect,HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import admin
from article.models import Article
from todo.models import Todo
from todo.todoLang import todoLanguage
from article.articleLang import articleLanguage
from users.userLang import userLanguage
from comment.commentLang import commentLanguage
from .language import *
import datetime
from users.models import UserProfile
import time
from django.conf import settings
from django.conf.urls.static import static

from apscheduler.schedulers.background import BackgroundScheduler
import smtplib
import ssl
from django.template import loader
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

context = {}
allArticles = 0
myTodos = 0
myArticles = 0
lang = en
isJobStarted = False


def check(req):

    global context
    global allArticles
    if(req.user.is_authenticated):
        allInfo(req)
        context = {
            "allArticles":allArticles,
            "myTodos":myTodos,
            "myArticles":myArticles
             }
    else:
        allArticles = len(Article.objects.filter(isPrivate = False))
        context = {"allArticles":allArticles}


def allInfo(req):
    global allArticles
    global myTodos
    global myArticles
    allArticles = len(Article.objects.filter(isPrivate = False))
    myTodos = len(Todo.objects.filter(author = req.user))
    myArticles = len(Article.objects.filter(author = req.user))



def mainPage(req):
    global lang
    global context

    check(req)
    if(req.user.is_authenticated):

        articles = Article.objects.filter(author = req.user)
        articles = articles.order_by('id')
        articles = articles[::-1]
        articles = list(articles[:4])
        context['articles'] = articles


        todos = Todo.objects.filter(author = req.user)
        todos = todos.order_by('date')
        todos = list(filter(lambda x: not x.iscompleted, todos))
        todos = todos[:4]
        context['todos'] = todos

        profile = UserProfile.objects.filter(user = req.user)
        if(profile):
            if(profile[0].profileImage):
                context['profileImage'] = profile[0].profileImage
    context['date'] = datetime.datetime.now()
    context['lang'] = lang
    return render(req,"index.html",context)



def searchArticle(req):
    global context
    global lang
    check(req)
    context['lang'] = lang
    keywords = req.GET.get('keywords')
    if(keywords):
        articles = Article.objects.filter(title__contains = keywords)
        context['articles'] = articles
    return render(req,'allarticles.html',context)

def searchUser(req):
    global context
    global lang
    check(req)
    keywords = req.GET.get('keywords')
    context['lang'] = lang
    if(keywords):
        users = User.objects.filter(username__contains = keywords)

        context['users'] = users
    return render(req,'allusers.html',context)



def language(req):
    global lang
    global context
    if(lang['language'] == "ENGLISH"): lang = en
    else: lang = tr
    context['lang'] = lang

    todoLanguage(lang)
    articleLanguage(lang)
    userLanguage(lang)
    commentLanguage(lang)
    return redirect(req.GET.get("currentPage"))



def startJob(req):
    global isJobStarted
    if(not isJobStarted):
        print("IT WILL START JOB")
        global job
        job = scheduler.add_job(tick,'interval', seconds=600)
        try:
            isJobStarted = True
            scheduler.start()
        except:
            pass
    return HttpResponseRedirect('/')
    


            

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url('startemailjob/',startJob,name = "startJob"),
    url('users/', include("users.userRoutes")),
    url("articles/",include("article.articleRoutes")),
    url("todos/",include("todo.todoRoutes")),
    url('searchArticle/',searchArticle,name = 'searchArticle'),
    url('searchUser/',searchUser,name = "searchUser"),
    url('comments/',include('comment.commentRoutes')),
    url('language/',language,name = "language"),
    url('^$',mainPage,name = "mainPage"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)





scheduler = BackgroundScheduler()
job = None

def tick():
    print("IT CHECKS @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    todos = Todo.objects.all()
    todos = todos.order_by('date')
    todos = list(filter(lambda x: not x.iscompleted, todos))
    for todo in todos:

        year = str(time.localtime(time.time()).tm_year)
        mon = str(time.localtime(time.time()).tm_mon)
        day = time.localtime(time.time()).tm_mday
        hour = time.localtime(time.time()).tm_hour
        if(len(mon) < 2):
            mon = '0' + mon

        todoYear = str(todo.date)[0:4]
        todoMon = str(todo.date)[5:7]
        todoDay = str(todo.date)[8:11]
        todoHour = (int(str(todo.date)[len(str(todo.date))-14:len(str(todo.date))-12]) + 3) % 24
        todoMin = (int(str(todo.date)[len(str(todo.date))-11:len(str(todo.date))-9]))
        # print("todo.date : ",todo.date)
        # print("todoHour : ",todoHour)
        # print("todoMin : ",todoMin)
        # datt = "{}/{}/{}  :  {}:{}".format(todoDay,todoMon,todoYear,todoHour,todoMin)
        # print(datt)

        if(todoYear == year and todoMon == mon):
            if((todoHour -1) % 24 == hour % 24):
                datt = "{}/{}/{}  :  {}:{}".format(todoDay,todoMon,todoYear,todoHour,todoMin)
                if(todoDay == "31"):
                    if(day == 1):
                        #Send Email
                        if(not todo.isEmailSent):
                                sendEmail(todo,datt)
                elif(int(todoDay) == day):
                        #SEND EMAIL
                    if(not todo.isEmailSent):
                        sendEmail(todo,datt)


        # print("Time to : ",todo.content)






def sendEmail(todo,datt):
    port = settings.EMAIL_PORT
    smtp_server = settings.EMAIL_HOST
    sender_email = settings.EMAIL_HOST_USER
    password = settings.EMAIL_HOST_PASSWORD
    receiver_email = todo.author.email
    subject = "Bugun Yapman Gerekenler !"
	

    # body = todo.content
    # message2 = 'Subject: {}\n\n{}'.format(subject, body)
    context = ssl.create_default_context()
    email_content = loader.render_to_string(
            'message.html',
            {
                'Content-Type': 'text/html; charset=utf-8',
                'Content-Disposition': 'inline',
                'Content-Transfer-Encoding': '8bit',
                'date': datetime.datetime.now().strftime('%a, %d %b %Y  %H:%M:%S %Z'),
                'X-Mailer': 'python',
                'subject': "Sayın {}, Görevinizi Yapmanız İçin Yaklaşık 1 saatiniz Kaldı. Todo Bilgileriniz : ".format(todo.author),
                'todo':  todo.content,
                'todoDate':datt,
                    }
        )
    

    MESSAGE = MIMEMultipart('alternative')
    MESSAGE['subject'] = subject
    MESSAGE['To'] = receiver_email
    MESSAGE['From'] = sender_email
    MESSAGE.preamble = """
Your mail reader does not support the report format.
Please visit us <a href="https://socialtodos.herokuapp.com/">online</a>!"""
 
    HTML_BODY = MIMEText(email_content, 'html')
 
    MESSAGE.attach(HTML_BODY)




    # print("IT IS HERE !")
    with smtplib.SMTP(smtp_server, port) as server:
        print("COME TO SEND EMAIL")
        server.ehlo()  # Can be omitted
        server.starttls(context=context)
        server.ehlo()  # Can be omitted
        # print("IT IS HERE ! @@@@@@@@@@@")
        server.login(sender_email, password)
        # print("INN SEND EMAIL METHOD BEFORE MESSAGING")
        try:
        	# html_message=message,
            server.sendmail(sender_email, receiver_email, MESSAGE.as_string())
            print("EMAIL GONDERILDI")
            todo.isEmailSent = True
            # print("EMAIL ATTI @@@@@@@@@@@@@@@@@@@@@@@")
            todo.save()

        except:
            print("EMAIL ATARKEN HATA ALDI")
        finally:
            print("QUIT FROM SERVER *****************************************************")
            server.quit()
           

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ckeditor.fields import RichTextField
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class UserProfile(models.Model):
    from .userLang import lang2
    user = models.OneToOneField(User)
    # username2 = models.CharField(max_length = 30,verbose_name = lang2['username'])
    # email = models.EmailField(max_length = 70,verbose_name = lang2['email'])
    # name = models.CharField(max_length = 30,verbose_name = lang2['firstname'])
    # surname = models.CharField(max_length = 30,verbose_name = lang2['lastname'])

    profileImage = models.ImageField(upload_to = 'profileimg',blank = True,null = True,verbose_name = "Resim Ekle/Add Picture")
    def __str__(self):
        return self.user.username

def create_profile(sender,**kwargs):
    if(kwargs['created']):
        userProfile = UserProfile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile,sender = User)

templates/about.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}

<div class = "container" style = "margin-top:20px;">
<h3>{{lang.about}}</h3>
<hr>
    <div class = "row">
    <div class = "container col-lg-6 col-xs-12 col-md-6" align="middle" style = " margin : auto auto;">
    <strong><img style = "witdh:18rem; height:18rem;"  alt = "Profile Image Is Empty" src = "{{profileImage.url}}"></strong>
    </div>
    <div class = "col-lg-6 col-xs-12 col-md-6" style = "margin-top:2rem;">
    <h4>{{lang.username}} : <strong><em>{{request.user.username}}</em></strong></h4>
    <h4>{{lang.firstname}} : <strong><em>{{request.user.first_name}}</em></strong></h4>
    <h4>{{lang.lastname}} : <strong><em>{{request.user.last_name}}</em></strong></h4>
    <h4>{{lang.email}} : <strong><em>{{request.user.email}}</em></strong></h4>
    <h4>{{lang.lastLogin}} : <strong><em>{{request.user.last_login}}</em></strong></h4>
    <h4>{{lang.joined}} : <strong><em>{{request.user.date_joined}}</em></strong></h4>
    <div style="text-align: center; margin-top: 1rem; margin-bottom:2rem;" class = "pull-right">
        <button type = "button" onclick="history.back()" class="btn btn-primary">{{lang.goBack}}</button>
        
    </div>
    </div>
    </div>






</div>
{% endblock body %}

templates/addprofileimage.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block body %}
<style>



#id_profileImage{


background-color: cornflowerblue;
height:3rem;
z-index: 3;
color: red;
display:none;

}

#id_profileImage2{


background-color: cornflowerblue;
height:3rem;
z-index: 3;
color: red;
text-align: center;
align-content: center;

}

</style>
<div class="container col-md-12 col-lg-12 col-xs-12">
    <div class="container">

        <h1>{{lang.editProfile}}</h1>
            <hr>
                <div class = "container col-lg-6 col-xs-12 col-md-6" align="middle" style = " margin : auto auto;">
                <strong><img style = "witdh:18rem; height:18rem;"  alt = "Profile Image Is Empty" src = "{{profileImage.url}}"></strong>
                </div>
            <hr>

            <form action="/users/addprofileimage/" method="POST" enctype="multipart/form-data">

                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
                <div class="input-group">
                    <div class="custom-file">
                      <!-- <input type="file" class="" id="inputGroupFile04"> -->
                      <input type="file" name="profileImage" color="yellow" class="custom-file-input" id="id_profileImage2" height="10rem" placeholder="CHOOSE FILE/RESIM SEÇ">
                    </div>
            
                      <label class="custom-file-label" for="inputGroupFile04">CHOOSE FILE / RESIM SEÇ</label>
                    </div><br>




                <button type="submit" class="btn btn-danger" onclick = "upload()">{{lang.save}}</button>
                <scan id = "uploadProgress"></scan>
            </form>
                    <div style="text-align: center; margin-top: 1rem; margin-bottom:2rem;" class = "pull-right">
                <button type = "button" onclick="history.back()" class="btn btn-primary">{{lang.goBack}}</button>

                </div>
        </div>


</div>
<br>
<br>
<script>
    function upload(){
        progress = document.getElementById("uploadProgress")
        progress.innerHTML = "<div class='alert alert-primary' style = 'margin-top : 0.5rem;'>Please Wait...</div>"
    }
</script>
{% endblock body %}

templates/addtodo.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
<style>

body {
    font: 1.2em/1.3 sans-serif;
    color: #222;
    font-weight: 400;
    padding: 5px;
    margin: 0;
    background: linear-gradient(#efefef, #999) fixed;
  }
  input {
    padding: 5px 0;
    font-size: 1.5em;
    font-family: inherit;
    width: 100px;
  }

  </style>
{% block body %}
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src = "{% static 'js/jquery-timepicker.js' %}"></script>
<script src = "{% static 'js/timePicker.js' %}"></script>

<div class="container">
    <div class="row">

        <div class="col align-self-center">
        <h1>{{lang.addTodo}}</h1>
            <hr>
            <form action="/todos/addtodo/" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <label for="date" style = "margin:0 1rem 0 0">{{lang.date}} :</label><input type="date" name = "date" style = "background-color: aquamarine; border-radius: 1rem;z-index: 1rem; box-shadow: 1px 1px 1px 1px; box-shadow: aqua;">
                <br><label for="date" style = "margin:0 1rem 0 0">{{lang.hour}} :</label><input type="text" class="time-picker form-control" id = "timePicker" value="Select Time"  placeholder="Select Time" name = "time" style = "background-color: aquamarine; border-radius: 1rem;z-index: 1rem; box-shadow: 1px 1px 1px 1px; box-shadow: aqua;" readonly>
                <br><br><button type="submit" class="btn btn-danger">{{lang.addTodo}}</button>
            </form>

            <script>
                jQuery(document).ready(function($){
                    $('#timePicker').hunterTimePicker({
              callback: function($){
                alert($.val());
              }
                });
                $('.time-picker').hunterTimePicker();
        
                });
        </script>

        </div>

    </div>
</div>
{% endblock body %}

templates/allarticles.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}

<h1 style = 'text-align:center; margin-top:1rem;'>{{lang.allArticles}}</h1>
<hr>
<div class="container" style="margin-top:1rem;">
    <div class="col-md-12 col-xs-12 col-lg-12 ">
        
              
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">{{lang.id}}</th>
      <th scope="col" style = "word-wrap: break-word;">{{lang.title}}</th>
      <th scope="col">{{lang.createdDate}}</th>

    </tr>
  </thead>
  <tbody>
  {% if articles %}
  {% for article in articles%}
  {% if not article.isPrivate %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href = "/articles/articledetail/{{article.id}}/">{{article.title}}</a></td>
      <td>{{article.createdDate}}</td>
      <td>
        <a href = "/articles/articledetail/{{article.id}}/"><button type="button" class="btn btn-primary"><i class="far fa-eye"></i></button></a>
      </td>
    </tr>
    {% endif %}

{% endfor %}
{% else %}
  <div class="alert alert-warning">
    {{lang.noArticle}}
</div>
{% endif %}
  </tbody>
</table>  
                
               

    </div>
</div>





{% endblock body %}

templates/changepassword.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">

        <div class="col align-self-center">
        <h1>{{lang.changePassword}}</h1>
            <hr>
            <form action="/users/changepassword/" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-danger">{{lang.save}}</button>
            </form>
        </div>

    </div>
        <div style="text-align: center; margin-top: 1rem; margin-bottom:2rem;" class = "pull-right">
        <button type = "button" onclick="history.back()" class="btn btn-primary">{{lang.goBack}}</button>
    </div>
</div>

{% endblock body %}

templates/changeusername.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">

        <div class="col align-self-center">
        <h1>{{lang.changeUsername}}</h1>
            <hr>
            <form action="/users/changeusername/" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-danger">{{lang.save}}</button>
            </form>
        </div>

    </div>
        <div style="text-align: center; margin-top: 1rem; margin-bottom:2rem;" class = "pull-right">
        <button type = "button" onclick="history.back()" class="btn btn-primary">{{lang.goBack}}</button>
    </div>
</div>

{% endblock body %}

templates/editprofile.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">

        <div class="col align-self-center">
        <h1>{{lang.editProfile}}</h1>
            <hr>
            <form action="/users/saveprofile/" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-danger">{{lang.save}}</button>
            </form>
        </div>

    </div>
    <div style="text-align: center; margin-top: 1rem; margin-bottom:2rem;" class = "pull-right">
        <button type = "button" onclick="history.back()" class="btn btn-primary">{{lang.goBack}}</button>
        
    </div>
</div>


{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% load static %}
{% block body %}


    <style>



        #bg {
          /* The image used */

          /* Full height */
          height: 100%;
        background-color: powderblue;

        }
        </style>

    {% if request.user.is_authenticated %}
<div  id = "bg">
<div class="container"   style = "margin : auto auto;text-align:center;" >
<br><br>
        <h2>{{lang.welcome}}, {% if request.user.is_authenticated %} {{ request.user.username }}  {% endif %}
                <div class = "container col-lg-6 col-xs-12 col-md-6" align="middle" style = " margin : auto auto; display:inline;">
                        <strong><img style = "witdh:6rem; height:6rem;"  class = "rounded-circle" src = "{{profileImage.url}}"></strong>
                        </div>
        </h2>
        <hr>
    <br>
    <div class="row">
        <div class="col-md-6 col-lg-4 col-xs-12">
        <a href = "/users/editprofile/"><scan style = "font-size:1.5rem;">{{lang.editProfile}}<br><img style = "width:6rem;height:6rem;"src={% static 'img/editProfile.png' %}></scan></a>
        <br><br>
        <a href = "/users/changepassword/"><scan style = "font-size:1.5rem;">{{lang.changePassword}}<br><img style = "width:6rem;height:6rem;"src={% static 'img/password.png' %}></scan></a>
        <br><br>
        <a href = "/users/changeusername/"><scan style = "font-size:1.5rem;">{{lang.changeUsername}}<br><img style = "width:8rem;height:8rem;"src={% static 'img/username.png' %}></scan></a>
        <br><br>
        <a href = "/users/addprofileimage/"><scan style = "font-size:1.4rem;">{{lang.changeProfilFoto}}<br><img style = "width:6rem;height:6rem;"src={% static 'img/profileFoto.png' %}></scan></a>
        <!-- <br><hr style = "background-color: red; width:100%; height:0.1rem; border-radius:50%;"><br> -->
        <br><br><br>
    </div>

    <div class="col-md-6 col-lg-4 col-xs-12"  style = "margin : auto auto;">
        <!-- RECENT comingTodos  -->

        <h3>{{lang.comingTodos}}</h3>
        <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">{{lang.date}}</th>
                <th scope="col" style = "word-wrap: break-word;">{{lang.content}}</th>
                <th scope="col" style = "word-wrap: break-word;">{{lang.todoStatus}}</th>
              </tr>
            </thead>
            <tbody>
                <hr>

                {% if todos %}
                     {% for todo in todos %}
                        <tr>
                        <th scope="row">{{todo.date}}</th>
                        <td><a href = "/todos/mytodos/">{{todo.content}}</a></td>
                        <td>
                        {% if todo.iscompleted %}

                        <img  style="width:3rem; height:3rem; ;" src={% static 'img/icon-yes.svg' %}>
                        {% else %}

                        <img  style="width:3rem; height:3rem;;" src={% static 'img/icon-no.svg' %}>

                        {% endif %}
                    </td>

                        </tr>
                    {% endfor %}
            {% else %}
                    <div class="alert alert-warning">
                        {{lang.noTodo}}
                    </div>
            {% endif %}

            </tbody>
        </table>
        <!-- <br><hr style = "background-color: red; width:100%; height:0.1rem; border-radius:50%;"><br> -->
        <br><br>

    </div>
    <div class="col-md-6 col-lg-4 col-xs-12"  style = "margin : auto auto;">
        <!-- RECENT ARTICLES   -->
        <h3>{{lang.recentArticles}}</h3>
        <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">{{lang.id}}</th>
                <th scope="col" style = "word-wrap: break-word;">{{lang.title}}</th>
                <th scope="col">{{lang.createdDate}}</th>

              </tr>
            </thead>
            <tbody>
                <hr>
                {% if articles %}
                     {% for article in articles %}
                        <tr>
                        <th scope="row">{{article.id}}</th>
                        <td><a href = "/articles/articledetail/{{article.id}}/">{{article.title}}</a></td>
                        <td>{{article.createdDate}}</td>
                        </tr>
                    {% endfor %}
            {% else %}
                    <div class="alert alert-warning">
                        {{lang.noArticle}}
                    </div>
            {% endif %}
            </tbody>
        </table>



    </div>
</div>
<br><br><br><br><br><br>
<br><br><br><br><br><br>
</div>
</div>

{% else %}

<div class="jumbotron" id = "bg">
    <h1>{{lang.pleaselogin}}</h1>
</div>

{% endif %}


























{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/timePicker.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
         <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
         <link rel="manifest" href="{% static 'js/manifest.webmanifest' %}">

</head>
<body>
    {% include "includes/navbar.html" %}
       {% if messages %}
        <div class = "container">
        {% for message in messages %}
            {% if message.tags == "info" %}
                <div class="alert alert-danger" style = "margin-top : 0.5rem;">{{ message }}</div>
            {% else %}
                <div class="alert alert-{{ message.tags}}" style = "margin-top : 0.5rem;">{{ message }}</div>
            {% endif %}
        </div>
           
        {% endfor %}
        {% endif %}
        {% block body %}
        
        {% endblock body %}


</body>


<script src = "{% static 'js/jquery.js' %}"></script>

<script src = "{% static 'js/bootstrap.min.js' %}"></script>

<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>



</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">

        <div class="col align-self-center">
        <h1>{{lang.login}}</h1>
            <hr>
            <form action="/users/login/" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-danger">{{lang.login}}</button>
            </form>
        </div>

    </div>
</div>

{% endblock body %}

templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Todos</title>
</head>
<body>
    <div class="container" style = "margin-top: 3rem; margin-bottom:8rem;">
        
        <div class="row">

            <div class="col">
            
             <h4><strong>{{ subject }}</strong></h4>
             <hr style = "margin-top:0; background-color:aqua">
             <strong>Todo Tarihi : </strong><em>{{ todoDate }}</em><br><hr style ="width:15rem; text-align: center;">
             <strong>Tamamlanma Durumu : </strong><em>Tamamlanmadı !</em><br><hr style ="width:15rem; text-align: center;">
             <strong>İçerik : </strong><em>{{ todo }}</em><br><hr style ="width:15rem; text-align: center;">
            


            </div>
            
        </div>
        

</body>
</html>

templates/myarticles.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}
<h1 style = 'text-align:center; margin-top:1rem;'>{{lang.myArticles}}</h1>
<hr>
<div class="container" style="margin-top:1rem;">
    <div class="col-md-12 col-xs-12 col-lg-12 ">
        
              
<table class="table table-bordered" style = "margin : auto auto;">
  <thead>
    <tr>
      <th scope="col">{{lang.id}}</th>
      <th scope="col" style = "word-wrap: break-word;">{{lang.title}}</th>
      <th scope="col">{{lang.createdDate}}</th>

    </tr>
  </thead>
  <tbody>
   {% if articles %}
  {% for article in articles%}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href = "/articles/articledetail/{{article.id}}/">{{article.title}}</a></td>
      <td>{{article.createdDate}}</td>
      <td>
        <a  href = "/articles/articledetail/{{article.id}}/"><button style = "margin:0.5rem 1rem;" type="button" class="btn btn-primary"><i class="far fa-eye"></i></button></a>
        <a href = "/articles/editarticle/{{article.id}}/"><button style = "margin:auto 1rem;" type="button" class="btn btn-success"><i class="fas fa-edit"></i></button></a>
        <a href = "/articles/deletearticle/{{article.id}}/"><button style = "margin:0.5rem 1rem;" type="button" class="btn btn-danger"><i class="far fa-trash-alt"></i></button></a>
      </td>
    </tr>
{% endfor %}
{% else %}
  <div class="alert alert-warning">
    {{lang.noArticle}}
</div>
{% endif %}
  </tbody>
</table>  
                
    </div>
</div>
<br>




{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container">

<h1>{{lang.register}}</h1>
<hr>
<form action="/users/register/" method = "POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type = "submit" class ="btn btn-danger">{{lang.register}}</button>
</form>

</div>
{% endblock body %}